"""Phase 3 search metrics and radar metadata

Revision ID: 6598d37405be
Revises: c7e41a9b2803
Create Date: 2026-09-09 13:16:49.170817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6598d37405be'
down_revision = 'c7e41a9b2803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radar_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), server_default='{}', nullable=False))

    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_review_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('accepted_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('queries_executed', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('candidates_after_rules', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('run_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), server_default='{}', nullable=False))

    # Lazily regenerate the revised title/institution matching key on rediscovery.
    op.execute(sa.text('UPDATE results SET identity_key = NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_column('run_metadata')
        batch_op.drop_column('candidates_after_rules')
        batch_op.drop_column('queries_executed')
        batch_op.drop_column('accepted_count')
        batch_op.drop_column('manual_review_count')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('radar_metadata')

    # ### end Alembic commands ###
