"""Phase 2 agent core and persistent observations

Revision ID: 989c25cbe36b
Revises: fc4d21f65ae0
Create Date: 2026-09-09 12:07:52.561728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989c25cbe36b'
down_revision = 'fc4d21f65ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_result_observations_result_id_results')),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], name=op.f('fk_result_observations_run_id_search_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_observations'))
    )
    with op.batch_alter_table('result_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_observations_result_id'), ['result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_result_observations_run_id'), ['run_id'], unique=False)

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reference_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('identity_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('source_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('source_metadata', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('analysis', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_results_url_key'), ['url_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_identity_key'), ['identity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_reference_key'), ['reference_key'], unique=False)

    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=24), server_default='INITIALIZING', nullable=False))
        batch_op.add_column(sa.Column('stage_history', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('trigger_type', sa.String(length=24), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('triggered_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('candidates_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('duplicate_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('analyzed_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('updated_results_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rejected_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('candidate_errors_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('input_tokens', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('output_tokens', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cached_tokens', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ai_calls', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('estimated_ai_cost', sa.Numeric(precision=18, scale=8), nullable=True))
        batch_op.add_column(sa.Column('error_kind', sa.String(length=40), nullable=True))


    # Phase 1 initialization records never had workers. Preserve them as failed
    # historical placeholders before enforcing one active run per radar.
    # Stop all application processes before applying this migration.
    op.execute(sa.text("UPDATE search_runs SET status='failed', finished_at=CURRENT_TIMESTAMP, "
                       "error_kind='legacy_placeholder', error_message='Phase 1 placeholder closed during Phase 2 migration.' "
                       "WHERE status IN ('initialized', 'running')"))
    op.execute(sa.text("UPDATE search_runs SET current_stage=CASE "
                       "WHEN status='completed' THEN 'COMPLETED' ELSE 'FAILED' END"))
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index('uq_search_runs_active_radar', ['radar_id'], unique=True, postgresql_where=sa.text("status IN ('initialized', 'running')"), sqlite_where=sa.text("status IN ('initialized', 'running')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_search_runs_active_radar', postgresql_where=sa.text("status IN ('initialized', 'running')"), sqlite_where=sa.text("status IN ('initialized', 'running')"))
        batch_op.drop_column('error_kind')
        batch_op.drop_column('estimated_ai_cost')
        batch_op.drop_column('ai_calls')
        batch_op.drop_column('cached_tokens')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')
        batch_op.drop_column('candidate_errors_count')
        batch_op.drop_column('rejected_count')
        batch_op.drop_column('updated_results_count')
        batch_op.drop_column('analyzed_count')
        batch_op.drop_column('duplicate_count')
        batch_op.drop_column('candidates_count')
        batch_op.drop_column('triggered_by')
        batch_op.drop_column('trigger_type')
        batch_op.drop_column('stage_history')
        batch_op.drop_column('current_stage')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_reference_key'))
        batch_op.drop_index(batch_op.f('ix_results_identity_key'))
        batch_op.drop_index(batch_op.f('ix_results_url_key'))
        batch_op.drop_column('analysis')
        batch_op.drop_column('source_metadata')
        batch_op.drop_column('source_status')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('identity_key')
        batch_op.drop_column('reference_key')
        batch_op.drop_column('canonical_url')
        batch_op.drop_column('url_key')

    with op.batch_alter_table('result_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_observations_run_id'))
        batch_op.drop_index(batch_op.f('ix_result_observations_result_id'))

    op.drop_table('result_observations')
    # ### end Alembic commands ###
