"""Initial radar memory schema

Revision ID: fc4d21f65ae0
Revises: 
Create Date: 2026-09-09 11:15:26.665161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4d21f65ae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_radars')),
    sa.UniqueConstraint('code', name=op.f('uq_radars_code'))
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radar_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ai_score >= 0 AND ai_score <= 100', name=op.f('ck_results_score_range')),
    sa.ForeignKeyConstraint(['radar_id'], ['radars.id'], name=op.f('fk_results_radar_id_radars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('radar_id', 'fingerprint', name='uq_results_radar_fingerprint')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_institution'), ['institution'], unique=False)
        batch_op.create_index('ix_results_radar_first_seen', ['radar_id', 'first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_reference'), ['reference'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radar_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_results_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('initialized', 'running', 'completed', 'failed')", name=op.f('ck_search_runs_valid_status')),
    sa.CheckConstraint('new_results_count >= 0', name=op.f('ck_search_runs_nonnegative_results')),
    sa.ForeignKeyConstraint(['radar_id'], ['radars.id'], name=op.f('fk_search_runs_radar_id_radars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_runs'))
    )
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index('ix_search_runs_radar_started', ['radar_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_search_runs_radar_started')

    op.drop_table('search_runs')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_reference'))
        batch_op.drop_index('ix_results_radar_first_seen')
        batch_op.drop_index(batch_op.f('ix_results_institution'))
        batch_op.drop_index(batch_op.f('ix_results_deadline'))

    op.drop_table('results')
    op.drop_table('radars')
    # ### end Alembic commands ###
