/* eslint-disable react-hooks/set-state-in-effect -- route changes intentionally start async API synchronization */
"use client";
import { useRadarRunSync } from "@/components/use-radar-run-sync";
import { runStatusLabel } from "@/components/run-status-banner";
import { ResultActions } from "@/components/result-actions";import { ReviewToast } from "@/components/review-toast";import { useReviewFeedback } from "@/components/use-review-feedback";import { afterConfirmedReview, reviewRefreshHref } from "@/lib/review-feedback";import { PreviousReview, ReviewChanges } from "@/components/result-review-context";import { radarNavigation } from "@/lib/radar-navigation";import { RunHistory } from "@/components/run-history";import Link from "next/link";import{useCallback,useEffect,useMemo,useRef,useState}from"react";import{useParams,useRouter,useSearchParams}from"next/navigation";import{api,ApiError}from"@/lib/api";import{formatDate,formatDateTime,formatMoney,formatProcedure,text}from"@/lib/format";import type{Page,Result,ResultPage,Run}from"@/types";import{DiscoveryBadge,RunContext,RunEmpty,RunScopeSwitch}from"@/components/run-scope";import{StatusBadge}from"@/components/status-badge";import{EmptyResults,ResultsError,TableSkeleton}from"@/components/table-state";import{TopContextBar}from"@/components/top-context-bar";import{radarName}from"@/lib/radars";
type SortKey="deadline"|"publication"|"estimate";
type Loaded={key:string;page:ResultPage};
type SideCount={key:string;total:number};

function DomainCells({item,radarId}:{item:Result;radarId:string}){
  if(radarId==="1")return <><td className="buyer-cell" data-label="Acheteur"><span className="clamp-2" title={text(item.institution)}>{text(item.institution)}</span></td><td className="hide-tablet" data-label="Lieu">{text(item.city)}</td><td className="money-cell" data-label="Estimation">{formatMoney(item.estimated_amount,item.estimated_currency||"MAD")}<small>{item.estimated_amount_tax_mode||""}</small></td><td className="date-cell hide-wide" data-label="Publication">{formatDate(item.publication)}</td><td className="date-cell deadline-cell" data-label="Échéance">{formatDateTime(item.deadline,item.deadline_time)}</td><td className="hide-wide" data-label="Type / procédure"><span className="type-label">{formatProcedure(item.procedure,item.announcement_type)}</span></td></>;
  if(radarId==="2")return <><td className="buyer-cell" data-label="Institution"><span className="clamp-2">{text(item.institution)}</span></td><td className="hide-tablet" data-label="Localisation">{text(item.city)}</td><td data-label="Maturité"><span className="type-label">{text(item.maturity)}</span></td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
  if(radarId==="3")return <><td className="buyer-cell" data-label="Institution"><span className="clamp-2">{text(item.institution)}</span></td><td data-label="Responsable">{text(item.person)}</td><td className="hide-tablet" data-label="Fonction">{text(item.position)}</td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
  if(radarId==="4")return <><td className="buyer-cell" data-label="Institution"><span className="clamp-2">{text(item.institution)}</span></td><td data-label="Type"><span className="type-label">{text(item.document_type)}</span></td><td className="hide-tablet" data-label="Statut juridique">{text(item.legal_status)}</td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
  return <><td className="buyer-cell" data-label="Bailleur"><span className="clamp-2">{text(item.funder||item.institution)}</span></td><td className="hide-tablet" data-label="Bénéficiaire">{text(item.beneficiary)}</td><td className="money-cell" data-label="Montant">{formatMoney(item.amount,item.currency||"MAD")}</td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
}

function DomainHeaders({radarId}:{radarId:string}){if(radarId==="1")return <><th>Acheteur</th><th className="hide-tablet">Lieu</th><th>Estimation</th><th className="hide-wide">Publication</th><th>Échéance</th><th className="hide-wide">Type / procédure</th></>;if(radarId==="2")return <><th>Institution</th><th className="hide-tablet">Localisation</th><th>Maturité</th><th>Date</th></>;if(radarId==="3")return <><th>Institution</th><th>Responsable</th><th className="hide-tablet">Fonction</th><th>Date</th></>;if(radarId==="4")return <><th>Institution</th><th>Type</th><th className="hide-tablet">Statut juridique</th><th>Date</th></>;return <><th>Bailleur</th><th className="hide-tablet">Bénéficiaire</th><th>Montant</th><th>Date</th></>}

export default function RadarPage(){
  const{radarId}=useParams<{radarId:string}>();const router=useRouter();const search=useSearchParams();const status=search.get("status")||"pending";const runId=search.get("run_id");const focusId=search.get("focus");const scopeAll=search.get("scope")==="all";const pageNumber=Math.max(1,Number(search.get("page")||1));
  const currentSearch=useRef(search);useEffect(()=>{currentSearch.current=search},[search]);
  const history=search.get("view")==="history";const {historyHref,tabHref}=radarNavigation(new URLSearchParams(search));const historyList=history&&!runId;
  const query=search.get("q")||"";const requestedSort=search.get("sort");const sort:SortKey=requestedSort==="publication"||requestedSort==="estimate"?requestedSort:"deadline";
  function updateControl(key:"q"|"sort",value:string){const params=new URLSearchParams(search);if(value)params.set(key,value);else params.delete(key);router.replace(`?${params}`,{scroll:false})}
  const runScoped=status==="pending"&&!!runId&&!scopeAll;
  const rememberedRun=runScoped?runId:(focusId||(scopeAll?runId:null));
  const viewKey=`${radarId}|${status}|${pageNumber}|${runScoped?`run:${runId}`:"backlog"}`;
  const[payload,setPayload]=useState<Loaded|null>(null);const[sideCount,setSideCount]=useState<SideCount|null>(null);const[error,setError]=useState(false);const[running,setRunning]=useState<Run|null>(null);const[focused,setFocused]=useState<Run|null>(null);const[notice,setNotice]=useState("");const[syncError,setSyncError]=useState("");const[historyRefresh,setHistoryRefresh]=useState(0);const[submitting,setSubmitting]=useState(false);const keepLaunch=useRef(false);const launchLock=useRef(false);const requestGen=useRef(0);
  const load=useCallback((silent=false)=>{const gen=++requestGen.current;if(historyList){if(silent)setHistoryRefresh(value=>value+1);return Promise.resolve(null)}if(!silent)setError(false);const main=runScoped?`/radars/${radarId}/results?status=pending&run_id=${runId}&page=${pageNumber}&page_size=20`:`/radars/${radarId}/results?status=${status}&page=${pageNumber}&page_size=20`;const side=!runScoped&&rememberedRun?`/radars/${radarId}/results?status=pending&run_id=${rememberedRun}&page=1&page_size=1`:null;if(!side)setSideCount(null);const mainReq=api<ResultPage>(main,{cache:"no-store"}).then(page=>{if(gen!==requestGen.current)return null;setPayload({key:viewKey,page});setError(false);setSyncError("");return page}).catch(reason=>{if(gen===requestGen.current){if(!silent)setError(true);else setSyncError(reason instanceof Error?reason.message:"Actualisation impossible. Nouvelle tentative automatique.")}return null});if(side){api<ResultPage>(side,{cache:"no-store"}).then(page=>{if(gen===requestGen.current)setSideCount({key:viewKey,total:page.total})}).catch(()=>undefined)}return mainReq},[radarId,status,pageNumber,runId,runScoped,rememberedRun,viewKey,historyList]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{keepLaunch.current=false},[radarId]);
  useEffect(()=>{if(keepLaunch.current)return;let cancelled=false;api<Page<Run>>(`/radars/${radarId}/runs?page_size=1`).then(page=>{if(!cancelled&&!keepLaunch.current)setRunning(page.items[0]??null)}).catch(()=>{if(!cancelled&&!keepLaunch.current)setRunning(null)});return()=>{cancelled=true}},[radarId]);
  useEffect(()=>{const selected=runScoped?runId:null;if(!selected){setFocused(null);return}let cancelled=false;api<Run>(`/runs/${selected}`).then(run=>{if(!cancelled)setFocused(run)}).catch(()=>{if(!cancelled)setFocused(null)});return()=>{cancelled=true}},[runId,runScoped]);
  const updateRun=useCallback((run:Run)=>{setRunning(run);setSyncError("");setFocused(current=>current?.id===run.id?run:current)},[]);
  const refreshResults=useCallback(()=>load(true),[load]);
  const syncFailed=useCallback((reason:unknown)=>setSyncError(reason instanceof Error?reason.message:"Actualisation impossible. Nouvelle tentative automatique."),[]);
  useRadarRunSync(radarId,running,updateRun,refreshResults,syncFailed);
  const visible=payload&&payload.key===viewKey?payload.page:null;
  const items=useMemo(()=>{const source=visible&&visible.total>0?visible.items:[];const needle=query.trim().toLocaleLowerCase("fr");const filtered=source.filter(item=>!needle||`${item.title} ${item.institution||""} ${item.reference||""}`.toLocaleLowerCase("fr").includes(needle));return [...filtered].sort((a,b)=>{if(sort==="estimate")return Number(b.estimated_amount||b.amount||0)-Number(a.estimated_amount||a.amount||0);return String(a[sort]||"9999").localeCompare(String(b[sort]||"9999"))})},[visible,query,sort]);
  const active=!!running&&["initialized","running"].includes(running.status);
  function pendingHref(next:number,scope:"run"|"all"){const params=new URLSearchParams(search);params.delete("view");params.delete("return");params.delete("scope");params.delete("run_id");params.delete("focus");params.set("status","pending");params.set("page",String(next));if(rememberedRun)params.set(scope==="run"?"run_id":"focus",rememberedRun);return `?${params}`}
  async function launch(){if(launchLock.current||active)return;launchLock.current=true;setSubmitting(true);setError(false);setNotice("");try{const result=await api<{run_id:number;status:string;launched_by?:Run["launched_by"]}>(`/radars/${radarId}/runs`,{method:"POST",body:"{}"});keepLaunch.current=true;setRunning({id:result.run_id,status:result.status,current_stage:"INITIALIZING",started_at:new Date().toISOString(),finished_at:null,new_results_count:0,updated_results_count:0,launched_by:result.launched_by??null});router.replace(`/radars/${radarId}?status=pending`)}catch(reason){if(reason instanceof ApiError&&reason.status===409){const page=await api<Page<Run>>(`/radars/${radarId}/runs?page_size=1`).catch(()=>null);if(page?.items[0])setRunning(page.items[0])}setNotice(reason instanceof ApiError?reason.message:"Impossible de lancer la recherche.")}finally{launchLock.current=false;setSubmitting(false)}}
  const refreshAfterReview=useCallback(async()=>{const next=await load(true);if(next){const href=reviewRefreshHref(new URLSearchParams(currentSearch.current),next);if(href)router.replace(href,{scroll:false})}},[load,router]);
  const confirmedReview=useCallback((id:number)=>{requestGen.current++;setPayload(current=>current&&current.key===viewKey?{...current,page:afterConfirmedReview(current.page,id)}:current)},[viewKey]);
  const {review,reviewing,notification,dismiss}=useReviewFeedback(refreshAfterReview,confirmedReview);
  const titleLabel=radarId==="3"?"Institution / signal":radarId==="4"?"Politique / texte":radarId==="5"?"Programme / financement":radarId==="2"?"Projet":"Objet";
  const queryString=(next:number)=>{const params=new URLSearchParams(search);params.set("page",String(next));return `?${params}`}
  const launchLabel=active||submitting?"En cours...":running?.status==="failed"?"Réessayer":"Lancer une recherche";
  const runCount=runScoped?(visible?visible.total:null):(sideCount&&sideCount.key===viewKey?sideCount.total:rememberedRun?null:null);
  const backlogCount=runScoped?(visible&&typeof visible.pending_total==="number"?visible.pending_total:null):(visible?visible.total:null);
  const runEmpty=!!visible&&runScoped&&visible.total===0&&!query.trim();
  const showSwitch=!history&&status==="pending"&&!!rememberedRun;
    return <><TopContextBar crumb={`Radar ${radarId}`} title={radarName(radarId)} actions={<button className="button" onClick={launch} disabled={active||submitting}>{launchLabel}</button>} /><main className="container radar-page">
  {running&&<div className="inline-notice" role="status">Recherche #{running.id} · {runStatusLabel(running.status)}{active?` · ${running.current_stage}`:` · ${running.new_results_count} nouveaux, ${running.updated_results_count} mis à jour`}</div>}
  {syncError&&<div className="inline-notice" role="alert">{syncError}</div>}
  <nav className="tabs" aria-label="Vues du Radar"><Link className={`tab ${!history&&status==="pending"?"active":""}`} aria-current={!history&&status==="pending"?"page":undefined} href={tabHref("pending")}>À traiter</Link><Link className={`tab ${!history&&status==="approved"?"active":""}`} aria-current={!history&&status==="approved"?"page":undefined} href={tabHref("approved")}>Validés</Link><Link className={`tab ${!history&&status==="rejected"?"active":""}`} aria-current={!history&&status==="rejected"?"page":undefined} href={tabHref("rejected")}>Rejetés</Link><Link className={`tab ${history?"active":""}`} aria-current={history?"page":undefined} href={historyHref}>Recherches précédentes</Link></nav>
  {history&&runId&&<div className="history-run-heading"><Link className="history-back" href={historyHref}>← Retour aux recherches précédentes</Link><RunContext id={runId} startedAt={focused?.id===Number(runId)?focused.started_at:null} launcher={focused?.id===Number(runId)?focused.launched_by?.name:null}/></div>}
  {historyList?<RunHistory radarId={radarId} historyHref={historyHref} refreshKey={historyRefresh}/>:<>
  {showSwitch&&<RunScopeSwitch runCount={runCount} backlogCount={backlogCount} runHref={pendingHref(1,"run")} backlogHref={pendingHref(1,"all")} runActive={runScoped}/>}
  <div className="result-toolbar"><div><strong>{visible?visible.total:"…"}</strong> résultat{visible?.total===1?"":"s"}</div><label className="search-control"><span>Rechercher</span><input value={query} onChange={event=>updateControl("q",event.target.value)} placeholder="Titre, acheteur, référence…"/></label><label className="sort-control"><span>Trier par</span><select value={sort} onChange={event=>updateControl("sort",event.target.value)}><option value="deadline">Échéance</option><option value="publication">Publication</option><option value="estimate">Estimation</option></select></label></div>
  {!history&&runScoped&&visible&&<RunContext id={focused?.id??runId} startedAt={focused?.started_at} launcher={focused?.launched_by?.name}/>}
  {notice&&<div className="inline-notice" role="status">{notice}</div>}{error?<ResultsError retry={()=>{void load()}}/>:!visible?<TableSkeleton/>:runEmpty?<RunEmpty href={history?tabHref("pending"):pendingHref(1,"all")}/>:visible.total===0||items.length===0?<EmptyResults label={query?"Aucun résultat ne correspond à votre recherche.":status==="pending"?"Aucun résultat à traiter.":"Aucun résultat dans cette vue."}/>:<div className="table-wrap result-table"><table><thead><tr><th>{titleLabel}</th><DomainHeaders radarId={radarId}/>{!runScoped&&<th>Lancée par</th>}<th>Statut</th><th className="actions-column">Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td className="title-cell" data-label={titleLabel}><span className="result-title">{item.title}</span>{item.reference&&<small>{item.reference}</small>}<ReviewChanges item={item}/></td><DomainCells item={item} radarId={radarId}/>{!runScoped&&<td className="launcher-cell" data-label="Lancée par">{item.launched_by?.name||"—"}</td>}<td data-label="Statut"><div className="result-review-status">{item.previous_review_status&&item.review_status==="PENDING"?<DiscoveryBadge discovery="UPDATED"/>:runScoped?<DiscoveryBadge observation={item.run_observation} discovery={item.discovery_status}/>:<StatusBadge review={item.review_status} discovery={item.discovery_status}/>}<PreviousReview item={item}/></div></td><td data-label="Actions"><ResultActions item={item} radarId={radarId} status={status} reviewing={reviewing[item.id]} onReview={review}/></td></tr>)}</tbody></table></div>}
  {visible&&visible.pages>1&&!runEmpty&&<nav className="pagination" aria-label="Pagination"><Link aria-disabled={pageNumber<=1} className={pageNumber<=1?"disabled":""} href={queryString(Math.max(1,pageNumber-1))}>Précédent</Link><span>Page {pageNumber} sur {visible.pages}</span><Link aria-disabled={pageNumber>=visible.pages} className={pageNumber>=visible.pages?"disabled":""} href={queryString(Math.min(visible.pages,pageNumber+1))}>Suivant</Link></nav>}</>}</main><ReviewToast notification={notification} dismiss={dismiss}/></>
}
