/* eslint-disable react-hooks/set-state-in-effect -- route changes intentionally start async API synchronization */
"use client";
import Link from "next/link";import{useCallback,useEffect,useMemo,useRef,useState}from"react";import{useParams,useRouter,useSearchParams}from"next/navigation";import{api,ApiError}from"@/lib/api";import{formatDate,formatDateTime,formatMoney,formatProcedure,text}from"@/lib/format";import type{Page,Result,Run}from"@/types";import{RunStatusBanner}from"@/components/run-status-banner";import{StatusBadge}from"@/components/status-badge";import{EmptyResults,ResultsError,TableSkeleton}from"@/components/table-state";import{TopContextBar}from"@/components/top-context-bar";import{radarName}from"@/lib/radars";
type SortKey="deadline"|"publication"|"estimate";

function ResultActions({item,radarId,status,reviewing,onReview}:{item:Result;radarId:string;status:string;reviewing:number|null;onReview:(item:Result,decision:"approve"|"reject")=>void}){
  const externalLabel=radarId==="1"?"Voir l’offre ↗":"Voir la source ↗";
  return <div className="compact-actions">{item.url?<a className="view-link" href={item.url} target="_blank" rel="noopener noreferrer">{externalLabel}</a>:<span className="source-unavailable">Source indisponible</span>}{status==="pending"&&<><button disabled={reviewing===item.id} onClick={()=>onReview(item,"approve")}>Valider</button><button className="reject-action" disabled={reviewing===item.id} onClick={()=>onReview(item,"reject")}>Rejeter</button></>}</div>
}

function DomainCells({item,radarId}:{item:Result;radarId:string}){
  if(radarId==="1")return <><td className="buyer-cell" data-label="Acheteur"><span className="clamp-2" title={text(item.institution)}>{text(item.institution)}</span></td><td className="hide-tablet" data-label="Lieu">{text(item.city)}</td><td className="money-cell" data-label="Estimation">{formatMoney(item.estimated_amount,item.estimated_currency||"MAD")}<small>{item.estimated_amount_tax_mode||""}</small></td><td className="date-cell hide-tablet" data-label="Publication">{formatDate(item.publication)}</td><td className="date-cell deadline-cell" data-label="Échéance">{formatDateTime(item.deadline,item.deadline_time)}</td><td className="hide-wide" data-label="Type / procédure"><span className="type-label">{formatProcedure(item.procedure,item.announcement_type)}</span></td></>;
  if(radarId==="2")return <><td className="buyer-cell" data-label="Institution"><span className="clamp-2">{text(item.institution)}</span></td><td className="hide-tablet" data-label="Localisation">{text(item.city)}</td><td data-label="Maturité"><span className="type-label">{text(item.maturity)}</span></td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
  if(radarId==="3")return <><td className="buyer-cell" data-label="Institution"><span className="clamp-2">{text(item.institution)}</span></td><td data-label="Responsable">{text(item.person)}</td><td className="hide-tablet" data-label="Fonction">{text(item.position)}</td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
  if(radarId==="4")return <><td className="buyer-cell" data-label="Institution"><span className="clamp-2">{text(item.institution)}</span></td><td data-label="Type"><span className="type-label">{text(item.document_type)}</span></td><td className="hide-tablet" data-label="Statut juridique">{text(item.legal_status)}</td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
  return <><td className="buyer-cell" data-label="Bailleur"><span className="clamp-2">{text(item.funder||item.institution)}</span></td><td className="hide-tablet" data-label="Bénéficiaire">{text(item.beneficiary)}</td><td className="money-cell" data-label="Montant">{formatMoney(item.amount,item.currency||"MAD")}</td><td className="date-cell" data-label="Date">{formatDate(item.publication)}</td></>;
}

function DomainHeaders({radarId}:{radarId:string}){if(radarId==="1")return <><th>Acheteur</th><th className="hide-tablet">Lieu</th><th>Estimation</th><th className="hide-tablet">Publication</th><th>Échéance</th><th className="hide-wide">Type / procédure</th></>;if(radarId==="2")return <><th>Institution</th><th className="hide-tablet">Localisation</th><th>Maturité</th><th>Date</th></>;if(radarId==="3")return <><th>Institution</th><th>Responsable</th><th className="hide-tablet">Fonction</th><th>Date</th></>;if(radarId==="4")return <><th>Institution</th><th>Type</th><th className="hide-tablet">Statut juridique</th><th>Date</th></>;return <><th>Bailleur</th><th className="hide-tablet">Bénéficiaire</th><th>Montant</th><th>Date</th></>}

export default function RadarPage(){
  const{radarId}=useParams<{radarId:string}>();const router=useRouter();const search=useSearchParams();const status=search.get("status")||"pending";const runId=search.get("run_id");const pageNumber=Math.max(1,Number(search.get("page")||1));
  const[data,setData]=useState<Page<Result>|null>(null);const[error,setError]=useState(false);const[running,setRunning]=useState<Run|null>(null);const[query,setQuery]=useState("");const[sort,setSort]=useState<SortKey>("deadline");const[reviewing,setReviewing]=useState<number|null>(null);const[notice,setNotice]=useState("");const keepLaunch=useRef(false);
  const load=useCallback(()=>{setError(false);const scoped=runId?`&run_id=${runId}`:"";return api<Page<Result>>(`/radars/${radarId}/results?status=${status}&page=${pageNumber}&page_size=20${scoped}`).then(setData).catch(()=>setError(true))},[radarId,status,pageNumber,runId]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{keepLaunch.current=false},[radarId]);
  useEffect(()=>{if(keepLaunch.current&&!runId)return;let cancelled=false;const request=runId?api<Run>(`/runs/${runId}`):api<Page<Run>>(`/radars/${radarId}/runs?page_size=1`).then(page=>page.items[0]??null);request.then(run=>{if(!cancelled)setRunning(run)}).catch(()=>{if(!cancelled&&runId)setRunning(null)});return()=>{cancelled=true}},[radarId,runId]);
  useEffect(()=>{if(!running||!["initialized","running"].includes(running.status))return;const timer=setInterval(()=>api<Run>(`/runs/${running.id}`).then(run=>{setRunning(run);if(!["initialized","running"].includes(run.status))load()}),3000);return()=>clearInterval(timer)},[running,load]);
  const items=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("fr");const filtered=(data?.items||[]).filter(item=>!needle||`${item.title} ${item.institution||""} ${item.reference||""}`.toLocaleLowerCase("fr").includes(needle));return [...filtered].sort((a,b)=>{if(sort==="estimate")return Number(b.estimated_amount||b.amount||0)-Number(a.estimated_amount||a.amount||0);return String(a[sort]||"9999").localeCompare(String(b[sort]||"9999"))})},[data,query,sort]);
  async function launch(){setError(false);try{const result=await api<{run_id:number;status:string;launched_by?:Run["launched_by"]}>(`/radars/${radarId}/runs`,{method:"POST",body:"{}"});keepLaunch.current=true;setRunning({id:result.run_id,status:result.status,current_stage:"INITIALIZING",started_at:new Date().toISOString(),finished_at:null,new_results_count:0,updated_results_count:0,launched_by:result.launched_by??null});if(runId)router.replace(`/radars/${radarId}?status=${status}`)}catch(reason){setNotice(reason instanceof ApiError?reason.message:"Impossible de lancer la recherche.")}}
  async function review(item:Result,decision:"approve"|"reject"){setReviewing(item.id);setNotice("");try{await api(`/results/${item.id}/${decision}`,{method:"POST",body:JSON.stringify({version:item.version})});setData(current=>current?{...current,items:current.items.filter(row=>row.id!==item.id),total:Math.max(0,current.total-1)}:current);setNotice(decision==="approve"?"Résultat validé.":"Résultat rejeté.")}catch{setNotice("L’action n’a pas pu être enregistrée. Rechargez les résultats.");await load()}finally{setReviewing(null)}}
  const titleLabel=radarId==="3"?"Institution / signal":radarId==="4"?"Politique / texte":radarId==="5"?"Programme / financement":radarId==="2"?"Projet":"Objet";
  const queryString=(next:number)=>`?status=${status}&page=${next}${runId?`&run_id=${runId}`:""}`;
  const busy=!!running&&["initialized","running"].includes(running.status);
  return <><TopContextBar crumb={`Radar ${radarId}`} title={radarName(radarId)} actions={<button className="button" onClick={launch} disabled={busy}>{busy?"Recherche en cours…":"Lancer une recherche"}</button>} /><main className="container radar-page">
  <nav className="tabs" aria-label="État des résultats"><Link className={`tab ${status==="pending"?"active":""}`} href={`?status=pending${runId?`&run_id=${runId}`:""}`}>À traiter</Link><Link className={`tab ${status==="approved"?"active":""}`} href={`?status=approved${runId?`&run_id=${runId}`:""}`}>Validés</Link><Link className={`tab ${status==="rejected"?"active":""}`} href={`?status=rejected${runId?`&run_id=${runId}`:""}`}>Rejetés</Link><Link className="tab" href={`/radars/${radarId}/runs`}>Recherches précédentes</Link></nav>
  <div className="result-toolbar"><div><strong>{data?.total??0}</strong> résultat{data?.total===1?"":"s"}</div><label className="search-control"><span>Rechercher</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Titre, acheteur, référence…"/></label><label className="sort-control"><span>Trier par</span><select value={sort} onChange={event=>setSort(event.target.value as SortKey)}><option value="deadline">Échéance</option><option value="publication">Publication</option><option value="estimate">Estimation</option></select></label></div>
  {notice&&<div className="inline-notice" role="status">{notice}</div>}{running&&<RunStatusBanner run={running}/>}{error?<ResultsError retry={load}/>:!data?<TableSkeleton/>:items.length===0?<EmptyResults label={query?"Aucun résultat ne correspond à votre recherche.":status==="pending"?"Aucun résultat à traiter.":"Aucun résultat dans cette vue."}/>:<div className="table-wrap result-table"><table><thead><tr><th>{titleLabel}</th><DomainHeaders radarId={radarId}/><th>Statut</th><th className="actions-column">Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td className="title-cell" data-label={titleLabel}><span className="clamp-2" title={item.title}>{item.title}</span>{item.reference&&<small>{item.reference}</small>}</td><DomainCells item={item} radarId={radarId}/><td data-label="Statut"><StatusBadge review={item.review_status} discovery={item.discovery_status}/></td><td data-label="Actions"><ResultActions item={item} radarId={radarId} status={status} reviewing={reviewing} onReview={review}/></td></tr>)}</tbody></table></div>}
  {data&&data.pages>1&&<nav className="pagination" aria-label="Pagination"><Link aria-disabled={pageNumber<=1} className={pageNumber<=1?"disabled":""} href={queryString(Math.max(1,pageNumber-1))}>Précédent</Link><span>Page {pageNumber} sur {data.pages}</span><Link aria-disabled={pageNumber>=data.pages} className={pageNumber>=data.pages?"disabled":""} href={queryString(Math.min(data.pages,pageNumber+1))}>Suivant</Link></nav>}</main></>
}
